# Generated by Django 5.2.2 on 2025-07-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile_default.png', null=True, upload_to='profile_images'),
        ),
    ]
