# Generated by Django 5.2.2 on 2025-07-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdetail',
            name='asset',
            field=models.ImageField(blank=True, default='tasks_asset/default_img.png', null=True, upload_to='tasks_asset'),
        ),
    ]
